apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-consumer
  labels:
    app: k8s-consumer
spec:
  selector:
    matchLabels:
      app: k8s-consumer
  template:
    metadata:
      labels:
        app: k8s-consumer
    spec:
      containers:
        - name: k8s-consumer
          image: k8s-consumer:latest
          ports:
            - containerPort: 20000
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-consumer
spec:
  ports:
    - port: 20000
      name: k8s-consumer
  selector:
    app: k8s-consumer