apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: k8s-consumer
deploy:
  kubectl:
    manifests: ["deployment.yaml"]
build:
  artifacts:
  - image: k8s-consumer
    context: ./
    docker: {}
