apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-provider-config
data:
  application.yml: |
    server.port: 20001
    spring.application.name: k8s-provider
    spring.cloud.kubernetes.reload.enabled: true
    spring.cloud.kubernetes.reload.monitoring-config-maps: true
    spring.cloud.kubernetes.reload.mode: polling
    spring.cloud.kubernetes.reload.period: 5000ms
    spring.cloud.kubernetes.client.namespace: default
    spring.cloud.kubernetes.client.service-account.name: default
    spring.jackson.serialization.INDENT_OUTPUT: true
    kubernetes.provider.hello: sayHello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-provider
  labels:
    app: k8s-provider
spec:
  selector:
    matchLabels:
      app: k8s-provider
  template:
    metadata:
      labels:
        app: k8s-provider
    spec:
      containers:
        - name: k8s-provider
          image: k8s-provider:latest
          ports:
            - containerPort: 20001
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - mountPath: /app/config
              name: k8s-provider-config
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: k8s-provider-config
          configMap:
            name: k8s-provider-config
            items:
              - key: application.yml
                path: application.yml
          
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-provider
spec:
  ports:
    - port: 20001
      name: k8s-provider
  selector:
    app: k8s-provider

