apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-provider
data:
  application.yml: |
    spring.jackson.serialization.INDENT_OUTPUT: true
    kubernetes.provider.hello: hello world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-provider
  labels:
    app: k8s-provider
spec:
  selector:
    matchLabels:
      app: k8s-provider
  template:
    metadata:
      labels:
        app: k8s-provider
    spec:
      containers:
        - name: k8s-provider
          image: k8s-provider:latest
          ports:
            - containerPort: 20001
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
          
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-provider
spec:
  ports:
    - port: 20001
      name: k8s-provider
  selector:
    app: k8s-provider

